#!/usr/bin/python

import sys

f = file("design.cfg")

sigmap = { 
  'B':'DCbool'
, 'c':'DCchar'
, 's':'DCshort'
, 'i':'DCint'
, 'l':'DClong'
, 'L':'DClonglong'
, 'f':'DCfloat'
, 'd':'DCdouble'
, 'p':'DCpointer'
}

apimap = {
  '_':''
, 's':'__declspec(stdcall)'
, 'f':'__declspec(fastcall)'
}

id = 0
maxargs = 0
sys.stdout.write("/* auto generated by mkcase.py (on stdout) */\n");
for line in f: 
  line = line.rstrip().lstrip()
  if len(line) == 0 or line[0] == '#': continue
  types = [];
  # args  = len(line)-1
  args = len(line)
  maxargs = max(maxargs, args)
  # api = apimap[ line[0] ]
  out = [ "VF",str(args),"(", str(id), "," ];
  for i in xrange(0,len(line)):   
    types += [ sigmap[ line[i] ] ]
  out += [ ",".join( types ), ",s_", line, ")\n" ]
  out = "".join(out)
  sys.stdout.write(out)
  id  += 1

sys.stderr.write("/* auto generated by mkcase (on stderr) */\n");
sys.stderr.write("".join( ["#define NCASES ",str(id),"\n"] ) )
sys.stderr.write("".join( ["#define MAXARGS ",str(maxargs),"\n"] ) )



