#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	Copyright 2007 Tassilo Philipp
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP = ..

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"

DIRS = suite suite2 ellipse callf plain#nm

.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

