#///////////////////////////////////////////////////
#
#	tests GNUmakefile
#	Copyright 2007 Daniel Adler
#
#///////////////////////////////////////////////////


TOP	=  ..
include $(TOP)/buildsys/gmake/prolog.gmake
DIRS	+= suite ellipse suite2 callf plain
include $(TOP)/buildsys/gmake/epilog.gmake

