APP = test_thunk
OBJS = test_thunk.o

SRCTOP ?= ../..
BLDTOP ?= ../..
CFLAGS = -I${SRCTOP}/dyncallback -I${SRCTOP}/dyncall
LDFLAGS = -L${BLDTOP}/dyncallback -ldyncallback_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

