APP = callback_plain
OBJS = callback_plain.o

SRCTOP ?= ../..
BLDTOP ?= ${SRCTOP}
CFLAGS = -I${SRCTOP}/dyncall
LDFLAGS = -L${BLDTOP}/dyncallback -ldyncallback_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

