APP = callback_suite
OBJS = env.o handler.o sigstrings.o invokers.o do_test.o main.o print.o signature_utils.o

SRCTOP ?= ../..
BLDTOP ?= ${SRCTOP}
CFLAGS += -I${SRCTOP}/dyncall -I${SRCTOP}/dyncallback
LDFLAGS += -L${BLDTOP}/dyncall -ldyncall_s -L${BLDTOP}/dyncallback -ldyncallback_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

