#//////////////////////////////////////////////////////////////////////////////
#
# Copyright (c) 2007,2009 Daniel Adler <dadler@uni-goettingen.de>, 
#                         Tassilo Philipp <tphilipp@potion-studios.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#//////////////////////////////////////////////////////////////////////////////

#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP=../..

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"


MODS	=	env handler sigstrings invokers do_test main print signature_utils
APP	=	callback_suite

CPPFLAGS	=
LDFLAGS		=
LIBS	=	"$(TOP)/dyncall/libdyncall_s.a" "$(TOP)/dyncallback/libdyncallback_s.a"


.PHONY: config clean-config
CONFIG_FILES	= _auto_config.h _auto_sigstrings.h _auto_invokers.h \
		   _auto_invoke_macros.h _auto_invoke_table.h 
CONFIG_FILES	+= _auto_signatures.txt

config: clean-config $(CONFIG_FILES) .SILENT

clean-config: clean
	rm -f $(CONFIG_FILES)

_auto_signatures.txt: 
	lua make-signatures.lua >$(.TARGET)

_auto_invokers.h: _auto_signatures.txt 
	lua make-invokers.lua <$(.ALLSRC) >$(.TARGET)

_auto_sigstrings.h: _auto_signatures.txt
	lua make-cstrings.lua <$(.ALLSRC) >$(.TARGET)

_auto_config.h: 
	lua make-config.lua >$(.TARGET)

_auto_invoke_macros.h:
	lua make-invoke-macros.lua >$(.TARGET)

_auto_invoke_table.h:
	lua make-invoke-table.lua >$(.TARGET)


.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

