APP      = callback_suite
OBJS     = env.o handler.o sigstrings.o invokers.o do_test.o main.o print.o signature_utils.o
SRCTOP   = ${VPATH}/../..
BLDTOP   = ../..
CFLAGS  += -I${SRCTOP}/dyncall -I${SRCTOP}/dyncallback
LDLIBS  += -L${BLDTOP}/dyncall -ldyncall_s -L${BLDTOP}/dyncallback -ldyncallback_s
.PHONY: all clean install
all: ${APP}
${APP}: ${OBJS} 
	${CC} ${CFLAGS} ${LDFLAGS} ${OBJS} ${LDLIBS} -o ${APP}
clean:
	rm -f ${APP} ${OBJS}
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test
