@ECHO OFF


SET BUILD_OS=windows

REM ------------------------
REM Help.
REM ------------------------
IF [%1]==[/?] (
	ECHO.
	ECHO Usage:
	ECHO   configure.bat [platform] [tool]
	ECHO.
	ECHO   platform: the platform to build dyncall for - this value
	ECHO             might be one of the following:
	ECHO             x86 ^(default^)
	ECHO             x64
	ECHO.
	ECHO   tool:     the tool to build dyncall with - this might be
	ECHO             one of the following:
	ECHO             msvc ^(default^)
	ECHO             gcc

REM ------------------------
REM Platforms.
REM ------------------------
) ELSE IF [%1]==[x64] (
        SET BUILD_ARCH=x64
) ELSE (
        SET BUILD_ARCH=x86
)

REM ------------------------
REM Tools.
REM ------------------------
IF [%2]==[gcc] (
	SET BUILD_TOOL=gcc
	SET BUILD_ASM=as
) ELSE (
	SET BUILD_TOOL=msvc
	SET BUILD_ASM=ml
)

SET INSTALL_DIR=%CD%\installed

ECHO # auto-generated by configure.bat >ConfigRules
ECHO BUILD_OS=%BUILD_OS%#>>ConfigRules
ECHO BUILD_ARCH=%BUILD_ARCH%#>>ConfigRules
ECHO BUILD_TOOL=%BUILD_TOOL%#>>ConfigRules
ECHO BUILD_ASM=%BUILD_ASM%#>>ConfigRules
ECHO INSTALL_DIR=%INSTALL_DIR%#>>ConfigRules

