@ECHO OFF

SET BUILD_OS=nds

REM ------------------------
REM Help.
REM ------------------------
IF [%1]==[/?] (
	ECHO.
	ECHO Nintendo DS ^(ARM9E^) configuration file. Assumes that devkitPro is installed.
	ECHO.
	ECHO Usage:
	ECHO   configure-nds.bat [platform]
	ECHO.
	ECHO   platform: the platform to build dyncall for - this value
	ECHO             might be one of the following:
	ECHO             arm9e_arm ^(default^)
	ECHO             arm9e_thumb

REM ------------------------
REM Platforms.
REM ------------------------
) ELSE IF [%1]==[arm9e_thumb] (
        SET BUILD_ARCH=arm_thumb
) ELSE (
        SET BUILD_ARCH=arm_arm
)

SET BUILD_TOOL=gcc_nds
SET BUILD_ASM=as

SET INSTALL_DIR=%CD%\installed

ECHO # auto-generated by configure-nds.bat >ConfigRules
ECHO BUILD_OS=%BUILD_OS%#>>ConfigRules
ECHO BUILD_ARCH=%BUILD_ARCH%#>>ConfigRules
ECHO BUILD_TOOL=%BUILD_TOOL%#>>ConfigRules
ECHO BUILD_ASM=%BUILD_ASM%#>>ConfigRules
ECHO INSTALL_DIR=%INSTALL_DIR%#>>ConfigRules

REM Check if DEVKITPRO is set.
IF [X%DEVKITPRO%]==[X] (
GOTO END_ABORT
)

REM Wee need at least 2 characters in the path.
IF [%DEVKITPRO:~0,1%]==[%DEVKITPRO%] (
GOTO END_ABORT
)

IF [%DEVKITPRO:~0,1%]==[/] (
ECHO DEVKITPRO_PATH=%DEVKITPRO:~1,1%:%DEVKITPRO:~2%#>>ConfigRules
) ELSE IF [%DEVKITPRO:~1,1%]==[:] (
ECHO DEVKITPRO_PATH=%DEVKITPRO%#>>ConfigRules
) ELSE (
GOTO END_ABORT
)

GOTO END

:END_ABORT
ECHO ERROR: Environment variable DEVKITPRO must be set to absolute devkitPro path.
DEL ConfigRules

:END

