@ECHO OFF


SET BUILD_OS=Windows

REM ------------------------
REM Help.
REM ------------------------
IF [%1]==[/?] (
	ECHO.
	ECHO Usage:
	ECHO   configure.bat [platform]
	ECHO.
	ECHO   platform: the platform to build dyncall for - this value
	ECHO             might be one of the following:
	ECHO             x86
	ECHO             x64
	ECHO.
	ECHO             if omitted it defaults to x86

REM ------------------------
REM Platforms.
REM ------------------------
) ELSE IF [%1]==[x64] (
        SET BUILD_ARCH=X64
) ELSE (
        SET BUILD_ARCH=X86
)

SET BUILD_TOOL=GCC
SET BUILD_ASM=as
SET INSTALL_DIR=%CD%\installed

ECHO # auto-generated by configure.bat >ConfigRules
ECHO BUILD_OS=%BUILD_OS%#>>ConfigRules
ECHO BUILD_ARCH=%BUILD_ARCH%#>>ConfigRules
ECHO BUILD_TOOL=%BUILD_TOOL%#>>ConfigRules
ECHO BUILD_ASM=%BUILD_ASM%#>>ConfigRules
ECHO INSTALL_DIR=%INSTALL_DIR%#>>ConfigRules

