M = ${MAKE} -f Makefile.generic

.PHONY: all clean install test

all:
	cd dyncall ; ${M}
	cd dynload ; ${M}
	cd dyncallback ; ${M}

clean:
	cd dyncall ; ${M} clean
	cd dynload ; ${M} clean
	cd dyncallback ; ${M} clean

install:
	cd dyncall ; ${M} install
	cd dynload ; ${M} install
	cd dyncallback ; ${M} install

test:
	cd test ; ${M}

osx-universal:
	${M} CPPFLAGS="-arch i386 -arch ppc -arch x86_64" MKLIB="libtool -static -o"

