.PHONY: all clean install tests run-tests clean distclean
all install:
	cd dyncall && ${MAKE} $@
	cd dynload && ${MAKE} $@
	cd dyncallback && ${MAKE} $@
clean:
	cd dyncall && ${MAKE} $@
	cd dynload && ${MAKE} $@
	cd dyncallback && ${MAKE} $@
	cd test && ${MAKE} $@
tests: all
	cd test && ${MAKE} all
run-tests: all
	cd test && ${MAKE} $@
distclean: clean
	rm -f Makefile.config
	find . -name "Makefile" | xargs rm

