SD = ../..
BD = ${SD}
CFLAGS += -I${SD}/dyncall
LDFLAGS += -L${BD}/dyncall -ldyncall_s
OBJS = globals.o invoke.o cases.o main.o
TARGETS = call_suite ${OBJS} 
.PHONY: all clean config config-random
all: ${TARGETS}
config:
	lua mk-cases.lua <design.txt >cases.h

config-random: 
	lua rand-sig.lua >cases.txt
	lua mk-cases.lua <cases.txt >cases.h
cases.o: cases.h 
call_suite: ${OBJS}
	${CC} ${CFLAGS} ${OBJS} ${LDFLAGS} -o $@
clean:
	rm -f ${TARGETS}

