MAKEFILE  = Makefile.embedded
MAKE_CMD  = ${MAKE} -f ${MAKEFILE}
TARGET	  = libsharedlib.so
OBJS	  = sharedlib.o
CPPFLAGS += -I../../dynload
LDFLAGS  += -Wl,-hlibsharedlib.so ../../dynload/libdynload_s.a

${TARGET}: ${OBJS}
	${CC} -shared -fPIC -o $@ $? ${LDFLAGS}
all: ${TARGET}
clean:
	rm -f ${TARGET} ${OBJS}

sun-gcc:
	CC=gcc CFLAGS="${CFLAGS} -fPIC" ${MAKE_CMD} all
