OBJS = dyncall_alloc_wx.o dyncall_args.o dyncall_callback.o dyncall_callback_arch.o dyncall_thunk.o
CFLAGS += -I../dyncall
libdyncallback_s.a(${OBJS}): ${OBJS}
	${AR} cr $@ $^
.PHONY: clean
clean:
	${RM} ${OBJS} libdyncallback_s.a
