APP = suite2
OBJS = case.o main.o

TOP = ../..
CFLAGS = -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncall -ldyncall_s
LINK = ${CXX}

all: ${APP}

.PHONY: all clean install autogen

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

autogen:
	python mkcase.py 1>case.h 2>config.h
