#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	Copyright 2007 Tassilo Philipp
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP=../..

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"


MODS	=	test_main
APP	=	plain

CPPFLAGS	=
LDFLAGS		=
LIBS	=	"$(TOP)/dyncall/libdyncall_s.a"

#AUTOS	=	test_framework.h


.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

