APP = plain
OBJS = test_main.o test_structs.o

TOP = ../..
CFLAGS = -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncall -ldyncall_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

