APP = plain
OBJS = test_main.o

TOP = ../..
CFLAGS = -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncall -ldyncall_s
#${TOP}/dyncall/libdyncall_s.a
# -L${TOP}/dyncall -ldyncall_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP}

clean:
	${RM} ${APP} ${OBJS}

