#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	Copyright 2007 Tassilo Philipp
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP   = ..  

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"

TARGETS=manual.pdf
manual.pdf!

.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

