#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	Copyright 2007 Tassilo Philipp
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP=../..

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"


MODS	=	main
APP	=	callf

CPPFLAGS	=
LDFLAGS		=
LIBS	=	"$(TOP)/dyncall/libdyncall_s.a"

.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

