# dcCallF test GNUmakefile
# Copyright 2007 Daniel Adler.

TOP		= ../..
APP		= test
MODS		= main
LINK_LIBPATHS	= $(TOP)/dyncall/$(BUILD_DIR)
LINK_LIBS	= dyncall_s

include $(TOP)/test/testmain/GNUmakerules

