# dcCallF test GNUmakefile
# Copyright 2007 Daniel Adler.

TOP		= ../..

include $(TOP)/buildsys/gmake/prolog.gmake

APP		= test
MODS		= main
LINK_PATHS	= $(TOP)/dyncall/$(BUILD_DIR)
LINK_LIBS	= dyncall_s

include $(TOP)/buildsys/gmake/epilog.gmake


