APP = syscall
OBJS = syscall.o

SRCTOP   = ../..
BLDTOP   = ../..
CFLAGS  += -I${SRCTOP}/dyncall
LDFLAGS += -ldyncall_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean 

${APP}: ${OBJS} 
	${CC} ${OBJS} ${LDFLAGS} -o ${APP} 

clean:
	${RM} ${APP} ${OBJS}

