APP = test_wx
OBJS = test_wx.o

TOP = ../..
CFLAGS = -I${TOP}/dyncallback
LDFLAGS = -L${TOP}/dyncallback -ldyncallback_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${LDFLAGS} ${OBJS} -o ${APP}

clean:
	${RM} ${APP} ${OBJS}

