APP = malloc_wx
OBJS = test_wx.o

TOP = ../..
CFLAGS = -I${TOP}/dyncallback -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncallback -ldyncallback_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP} ${TARGET_ARCH}

clean:
	${RM} ${APP} ${OBJS}

