APP = suite_floats
OBJS = case.o main.o

TOP = ../..
CFLAGS = -I${TOP}/dyncall
LDFLAGS = -L${TOP}/dyncall -ldyncall_s
LINK = ${CXX}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${LDFLAGS} ${OBJS} -o ${APP}

clean:
	${RM} ${APP} ${OBJS}

