APP  = suite_floats
OBJS = case.o main.o
TOP     = ../..
CFLAGS  += -I${TOP}/dyncall
LDFLAGS += -L${TOP}/dyncall -ldyncall_s

all: ${APP}

%.o: %.cpp
	${CXX} -c ${CPPFLAGS} ${CXXFLAGS} $< ${OUTPUT_OPTION} 

.PHONY: all clean 

${APP}: ${OBJS} 
	${CXX} ${OBJS} ${LDFLAGS} -o ${APP}

clean:
	rm -f ${APP} ${OBJS}

