APP = resolve_self
OBJS = main.o

TOP = ../..
CFLAGS = -I${TOP}/dynload
LDFLAGS = -L${TOP}/dynload -ldynload_s
LINK = ${CC}

all: ${APP}

.PHONY: all clean install

RM      ?= rm -f
AR      ?= ar
MKDIR	?= mkdir
INSTALL	?= install -p

${APP}: ${OBJS} 
	${LINK} ${OBJS} ${LDFLAGS} -o ${APP}

clean:
	${RM} ${APP} ${OBJS}

