#///////////////////////////////////////////////////
#
#	bsdmake makefile
#	Copyright 2007 Tassilo Philipp
#	BSDmakefile
#
#///////////////////////////////////////////////////


TOP=../..

.include "$(TOP)/buildsys/bsdmake/prolog.bsdmake"


MODS	=	nm
APP	=	nm

CPPFLAGS	=
LDFLAGS		=
LIBS	=	"$(TOP)/dyncall/libdyncall_s.a" "$(TOP)/dynload/libdynload_s.a"

.include "$(TOP)/buildsys/bsdmake/epilog.bsdmake"

