# dynload example 'nm' GNUmakefile 
# sample program that dumps symbols found in dynamic librarys
# Copyright 2007 Daniel Adler.

TOP		= ../..

APP		= nm
MODS		= nm
LDFLAGS		= -L$(TOP)/dynload/$(BUILD_DIR)
LDLIBS		= -ldynload_s

include $(TOP)/test/testmain/GNUmakerules


