APP = nm
OBJS = nm.o

TOP = ../..
CFLAGS  += -I${TOP}/dynload
LDFLAGS += -L${TOP}/dynload -ldynload_s 
# Works on: Darwin, NetBSD.
# Linux: add '-ldl'

all: ${APP}

.PHONY: all clean

${APP}: ${OBJS} 
	${CC} ${OBJS} ${LDFLAGS} -o ${APP} 

clean:
	rm -f ${APP} ${OBJS}

